image: microsoft/dotnet-framework:4.7.2-sdk

stages:
    - build
    - test

variables:
    test: "Example.Test"

before_script:
    - "cd TrayTool"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"